theme = ["sam", "hugo-shortcode-gallery"]

baseurl                  = "https://wedding.markfrancis.io"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    #favicon              = "sam.ico"
    homepage             = ""                           # What to call the home page link, link will not be rendered if empty

[[params.videoBackground.sources]]
    source  = "/sample_video.mp4"
    type    = "video/mp4"
    poster  = "/background.png"
[params.videoBackground]
    overlay = "rgba(0, 0, 0, 0.4)" # optional

[[params.mainMenu]]
    link = "gallery"
    text = "Alan and Julie"

[imaging]
    quality = 75