#version: '3'

# services:
#   hugo:
#     #env_file: .env
#     build:
#       context: .
#       args:
#         ALPINE_VERSION: ${ALPINE_VERSION}
#         HUGO_VERSION: ${HUGO_VERSION}
#     volumes:
#       - .:/srv/hugo
#     ports:
#       - 1313:1313

server:
  image: klakegg/hugo:0.101.0-ext-alpine
  command: server
  volumes:
    - ".:/src"
  ports:
    - "1313:1313"